require("kumsuzM.plugins-setup") -- sets up packer and plugins
require("kumsuzM.core.options") -- sets up our preffered vim options
require("kumsuzM.core.keymaps")
require("kumsuzM.plugins-config.comment")
require("kumsuzM.plugins-config.nvim-tree")
require("kumsuzM.plugins-config.lualine")
require("kumsuzM.plugins-config.telescope")
require("kumsuzM.plugins-config.nvim-cmp")
require("kumsuzM.plugins-config.lsp.mason")
require("kumsuzM.plugins-config.lsp.lspsaga")
require("kumsuzM.plugins-config.lsp.lspconfig")
require("kumsuzM.plugins-config.lsp.null-ls")
require("kumsuzM.plugins-config.autopairs")
require("kumsuzM.plugins-config.treesitter")
require("kumsuzM.plugins-config.gitsigns")
require("kumsuzM.plugins-config.vimtex")
